wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.16
    start_time: 1750246690
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 16
      4: 3.10.16
      5: 0.12.21
      8:
      - 5
architecture:
  desc: null
  value: SimpleAutoencoder_BN_LeakyReLU
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 30
latent_dim:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0005
model_name:
  desc: null
  value: theia-tiny-patch16-224-cddsv
validation_split:
  desc: null
  value: 0.1
weight_decay:
  desc: null
  value: 1.0e-05
